// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxGC_tWMrqmj-XrhBaQ5Xq56ZkGffb3D4',
    appId: '1:490828871968:web:ef126297b3fd05ca473f45',
    messagingSenderId: '490828871968',
    projectId: 'pizzaconfigurator',
    authDomain: 'pizzaconfigurator.firebaseapp.com',
    storageBucket: 'pizzaconfigurator.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSCWJNJWGaNVYQ2EGLdo0bOiXyz6o72Nw',
    appId: '1:490828871968:android:42fea0dc27bf3a5e473f45',
    messagingSenderId: '490828871968',
    projectId: 'pizzaconfigurator',
    storageBucket: 'pizzaconfigurator.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDg0PmXkZcwCdrbJoQpcAjLCQVkup_WaBQ',
    appId: '1:490828871968:ios:4652b5bc364d008e473f45',
    messagingSenderId: '490828871968',
    projectId: 'pizzaconfigurator',
    storageBucket: 'pizzaconfigurator.appspot.com',
    iosClientId: '490828871968-tv3r93urccrsp69rbol2sp8o301tbjig.apps.googleusercontent.com',
    iosBundleId: 'com.strawanzer',
  );
}
